### ISSUE TITLE
onDialogInitCallback observable uses onDialogDisplayCallback subject

### ISSUE THREAD

**Issue by mstieranka** [halloverden/ngx-cookiebot#1]
This doesn't seem intentional and probably should be fixed.

https://github.com/halloverden/ngx-cookiebot/blob/79ae7342b07790bbc212213c2c26331217b77605/projects/ngx-cookiebot/src/lib/ngx-cookiebot.service.ts#L37

**Comment by andreaslarssen** [comment]
> This doesn't seem intentional and probably should be fixed.
> 
> https://github.com/halloverden/ngx-cookiebot/blob/79ae7342b07790bbc212213c2c26331217b77605/projects/ngx-cookiebot/src/lib/ngx-cookiebot.service.ts#L37

Good catch. PR's welcome. Will otherwise fix when I have a minute
