### ISSUE TITLE
Constructor gets called with empty object

### ISSUE THREAD

**Issue by jflament** [halloverden/ngx-cookiebot#11]
Hi,
I followed the steps described [here](https://github.com/halloverden/ngx-cookiebot/tree/main/projects/ngx-cookiebot#readme). When loading my website in the browser I get this error in the console:
`Wrong loadScript config value. Please provide a correct value in the Cookiebot config`

cookiebot.config.ts:
```
export class CookiebotConfig extends NgxCookiebotConfig {
  blockingMode: 'manual';
  cbId: '***';
  cdn: 'com';
  culture?: 'en';
  framework?: 'IAB';
  level?: 'implied';
  loadScript: true;
  type?: 'optout';
}
```

When the execution reaches the method `_verifyConfig`, `this.cookiebotConfig.loadScript` is `undefined`.
Same thing for `cdn`, `cbId`, `blockingMode`.
Actually, the constructor gets called with an empty object as parameter.

Any idea what the problem might be?

Thanks!

**Comment by andreaslarssen** [comment]
Hi.

Can't say I've seen it before. What version are you on? I know there was some trouble with the validation in an older version, but that should have been deprecated.

**Comment by jflament** [comment]
I'm using v2.0.3 of the [package](https://www.npmjs.com/package/@halloverden/ngx-cookiebot).

**Comment by andreaslarssen** [comment]
I need to see if I can reproduce, and I'm sorry to say that it's probably going to take a few days before I have the time. If you have the time, we're super happy for PR's.

**Comment by andreaslarssen** [comment]
I'm sorry to say there isn't. It also requires a cookiebot account, so I haven't gotten around to creating one, but you should be able to clone the repo and config the lib to your account and test it locally

**Comment by andreaslarssen** [comment]
Did you follow the docs when setting up the config?

```
// app.module.ts
import { NgxCookiebotModule } from '@halloverden/ngx-cookiebot';
import { CookiebotConfig } from '@config/cookiebot.config';

@NgModule({
  imports: [
    NgxCookiebotModule.forRoot(CookiebotConfig)
  ]
})
```

**Comment by jflament** [comment]
Yes I followed the docs and modified the files accordingly.
I already have a Cookiebot account.

**Comment by groninge01** [comment]
This works:

```
export class CookiebotConfig extends NgxCookiebotConfig {
  blockingMode: 'auto' | 'manual' | string = 'auto';
  cbId = '****';
  cdn: 'com' | 'eu' | string = 'com';
  culture?: string;
  framework?: string;
  level?: string;
  loadScript = true;
  type?: string;
}
```

**Comment by jflament** [comment]
> This works:
> 
> ```
> export class CookiebotConfig extends NgxCookiebotConfig {
>   blockingMode: 'auto' | 'manual' | string = 'auto';
>   cbId = '****';
>   cdn: 'com' | 'eu' | string = 'com';
>   culture?: string;
>   framework?: string;
>   level?: string;
>   loadScript = true;
>   type?: string;
> }
> ```

I'm sorry, I don't see how copying [a part of the current documentation](https://github.com/halloverden/ngx-cookiebot/tree/main/projects/ngx-cookiebot#1-configure-service) is going to help anyone.

**Comment by ElCarsten** [comment]
Hey,

I got the same error as mentioned above.
I am also at version 2.0.3.

I modified the your source code in node_modules to see which config data gets passed to your constructor and its empty as well.

```
cookiebotConfig {}

[[Prototype]]: NgxCookiebotConfigconstructor: class CookiebotConfiglength: 0name: "CookiebotConfig"prototype: NgxCookiebotConfig {constructor: ƒ}arguments: (...)caller: (...)[[FunctionLocation]]: app.module.ts:76[[Prototype]]: class NgxCookiebotConfig[[Prototype]]: Object
instrument.js:109 Error: Wrong loadScript config value. Please provide a correct value in the Cookiebot config
    at NgxCookiebotService._verifyConfig (halloverden-ngx-cookiebot.js:228:1)
    at new NgxCookiebotService (halloverden-ngx-cookiebot.js:74:1)
    at Object.factory (core.js:17436:1)
    at R3Injector.hydrate (core.js:17247:42)
    at R3Injector.get (core.js:16997:1)
    at injectInjectorOnly (core.js:940:1)
    at ɵɵinject (core.js:950:1)
    at injectArgs (core.js:1067:1)
    at Object.factory (core.js:17417:1)
    at R3Injector.hydrate (core.js:17247:42)
    at R3Injector.get (core.js:16997:1)
    at injectInjectorOnly (core.js:940:1)
```

This is my conf

`export class CookiebotConfig extends NgxCookiebotConfig {
	loadScript: true;
	blockingMode: "auto";
	cbId: "********-****-*****";
	cdn: "eu";
}`

if I change this conf to the plain documentation it is working as well:

`export class CookiebotConfig extends NgxCookiebotConfig {
	blockingMode: "auto" | "manual" | string = "auto";
	cbId = "****";
	cdn: "com" | "eu" | string = "com";
	culture?: string;
	framework?: string;
	level?: string;
	loadScript = true;
	type?: string;
}`

**Comment by ElCarsten** [comment]
Nevermind I think I got it.

I think the documentation is a bit misleading here. The config only has to be replaced by the own key and otherwise remain as stated in the documentation. I think we made the mistake of adjusting the config too much.

It works for me now. Thanks for the repo and the great maintenance.

**Comment by ElCarsten** [comment]
@andreaslarssen works like a charm! Thank you for looking into this.

**Comment by andreaslarssen** [comment]
@ElCarsten good to hear, sorry it took so long to figure out
