### ISSUE TITLE
Are you going to update to be compatible with angular 15?

### ISSUE THREAD

**Issue by davidestrim** [halloverden/ngx-cookiebot#13]

**Comment by andreaslarssen** [comment]
In theory it should be enough to just up the version, but it needs to be tested. Are you up for a PR?

**Comment by davidestrim** [comment]
Yea, lets go and thanksEl El mar, 14 mar 2023 a las 10:20, Andreas Larssen ***@***.***> escribió:
In theory it should be enough to just up the version, but it needs to be tested. Are you up for a PR?

**Comment by davidgvf** [comment]
@ErikIw-HalloVerden pr #14

**Comment by davidgvf** [comment]
@ErikIw-HalloVerden updated #14

**Comment by andreaslarssen** [comment]
Closed by #14
