### ISSUE TITLE
SSR issues with getWindow() function

### ISSUE THREAD

**Issue by dydome** [halloverden/ngx-cookiebot#5]
Hello guys, we are facing issues with our application when we are building it in SSR mode. The problem is that in `NgxCookiebotService` there is a method that is using directly window object `function getWindow(): any {
  return window;
}`
this causes issues with SSR.

There are a couple of possible solutions to test, but it is hard to test them locally :(

1. solution

`constructor(@Inject(DOCUMENT) private document: Document) {}

  getWindow(): Window | null {
    return this.document.defaultView;
  }`

2. Solution
There are suggestions to use `domino` https://errorsfixing.com/referenceerror-window-is-not-defined-angular-universal/

3. Solution
We can try to use https://www.npmjs.com/package/ssr-window

**Comment by jegorovedgar** [comment]
and one more possible solution is to use:
https://www.npmjs.com/package/ngx-window-token
`constructor(@Inject(WINDOW) _window) { }`

**Comment by andreaslarssen** [comment]
@dydome You're right, SSR is not supported as it is now. That should have been documented, sorry about that. I'll see if I can come up with a release candidate for you to test as soon as I got some time. If you wanna take a stab before that, PR's are most welcome. Thanks for reporting.

**Comment by Maretzky85** [comment]
Hi, I actually got this lib working for SSR, but only in a way, that I am vomiting setup altogether for SSR, and initializing only for client side.
It's done without any additional dependencies.

I don't know if I know how to do proper PR ;) 
But if that's something interesting than I can share my solution :)

**Comment by andreaslarssen** [comment]
@Maretzky85 Would be nice if you share here for future reference and ideas

**Comment by Maretzky85** [comment]
That is my working solution. May not be best (for sure), but works for SSR.
https://github.com/halloverden/ngx-cookiebot/pull/18

**Comment by Maretzky85** [comment]
@erichjsonfosse I confirm it's working fine :)

**Comment by erichjsonfosse** [comment]
@Maretzky85 
Sweet! 3.1.0 is now published! Thanks for contributing :+1:
