### ISSUE TITLE
GDPR Conform Configuration

### ISSUE THREAD

**Issue by TanjaBayer** [halloverden/ngx-cookiebot#7]
Hi, 

we thought about using this package for integrating cookiebot website, however I just found that there is a problem with the general configuration and where the scripts are loaded from. You have hardcoded the CDN url in the onInit Function https://github.com/halloverden/ngx-cookiebot/blob/main/projects/ngx-cookiebot/src/lib/ngx-cookiebot.component.ts#L31.

According to the support there is a Eurpoean CDN, so it would be cool if it could be configured via the config, like other details:

https://support.cookiebot.com/hc/en-us/articles/4530208762396-Cookiebot-CMP-European-CDN-solution

Would you accept a pull request on that?

**Comment by andreaslarssen** [comment]
Hi.

Thanks for the issue, and absolutely. Was not aware there where two urls

**Comment by andreaslarssen** [comment]
@TanjaBayer I released a 2.0.0 version. You'll see that I changed some docs, and how the config parameters work as I wanted ppl to have a relationship to those new config params. 

Check it out and let me know how it goes. Thanks for the PR!
