### ISSUE TITLE
Build w/ newer (Ivy based) Angular version

### ISSUE THREAD

**Issue by andreaslarssen** [halloverden/ngx-cookiebot#9]

**Comment by JesseDeBruijne** [comment]
+1

Starting in Angular 16, NGCC packages can no longer be used. This is now a blocker for everyone to update to Angular 16.

For reference, you'll see an error like this when building:

>Error: NgxCookiebotModule does not have a module def (ɵmod property)

**Comment by andreaslarssen** [comment]
@JesseDeBruijne I am aware and sorry to say I won't get around to do this in a while. If anyone's up for a PR, it would be most welcome

**Comment by JesseDeBruijne** [comment]
I've created a PR updating Angular to v16, which now build using Ivy by default:

https://github.com/halloverden/ngx-cookiebot/pull/16
